# fly.toml file generated for groopy-gateway on 2023-04-10T17:40:56+02:00

app = "groopy-gateway"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "mad"

[[services]]
  protocol = "tcp"
  internal_port = 8095
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
