server:
  port: 8095
  address: localhost
spring:
  application.name: groopy-gateway

room-service:
  host: "http://localhost:8090/"

user-service:
  host: "user-service.fly.dev:8091/"

grpc:
  server:
    security:
      enabled: false
  client:
    userService:
                address: "static://localhost:8071"
                negotiationType: PLAINTEXT
    roomService:
                address: "static://localhost:8070"
                negotiationType: PLAINTEXT