server:
  port: 8095
  address: localhost
spring:
  config:
    import: file:.env[.properties]
  application.name: groopy-gateway
  mvc:
    dispatch-options-request: true

grpc:
  server:
    security:
      enabled: false
  client:
    userService:
                address: "static://localhost:8071"
                negotiationType: PLAINTEXT
    wallService:
                address: "static://localhost:8070"
                negotiationType: PLAINTEXT
    chatService:
                address: "static://localhost:8072"
                negotiationType: PLAINTEXT

groopy:
  app:
    apiKey:
      header: "x-api-key"
      value: ${GATEWAY_API_KEY}
