server:
  port: 8095
  address: localhost
spring:
  application.name: groopy-gateway

grpc:
  server:
    security:
      enabled: false
  client:
    userService:
                address: "static://localhost:8071"
                negotiationType: PLAINTEXT
    wallService:
                address: "static://localhost:8070"
                negotiationType: PLAINTEXT
    chatService:
                address: "static://localhost:8072"
                negotiationType: PLAINTEXT