server:
  port: 8095
  address: localhost
spring:
  application.name: groopy-gateway

grpc:
  server:
    security:
      enabled: false
  client:
    userService:
                address: "static://localhost:8071"
                negotiationType: PLAINTEXT
    wallService:
                address: "static://localhost:8070"
                negotiationType: PLAINTEXT
    chatService:
                address: "static://localhost:8072"
                negotiationType: PLAINTEXT

groopy:
  app:
    apiKey:
      header: "x-api-key"
      value: "ce602c1f-865f-44c2-bda0-184766fbb805"