server:
  address: 0.0.0.0
  port: 8095
spring:
  application.name: groopy-gateway

grpc:
  server:
    security:
      enabled: false
  client:
    userService:
      address: "static://userservice:8071"
      negotiationType: PLAINTEXT
    wallService:
      address: "static://wallservice:8070"
      negotiationType: PLAINTEXT
    chatService:
      address: "static://chatservice:8072"
      negotiationType: PLAINTEXT

groopy:
  app:
    token:
      header: "x-auth-token"
    apiKey:
      header: "x-api-key"
      value: "ce602c1f-865f-44c2-bda0-184766fbb805"