server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8095}

spring:
  application.name: groopy-gateway
  mvc:
    dispatch-options-request: true

grpc:
  server:
    security:
      enabled: false
  client:
    userService:
      address: "static://userservice:8071"
      negotiationType: PLAINTEXT
    wallService:
      address: "static://wallservice:8070"
      negotiationType: PLAINTEXT
    chatService:
      address: "static://chatservice:8072"
      negotiationType: PLAINTEXT
    threadsService:
      address: "static://threadsservice:8073"
      negotiationType: PLAINTEXT

groopy:
  app:
    apiKey:
      header: "x-api-key"
      value: ${GATEWAY_API_KEY}
