server:
  address: 0.0.0.0
  port: 8095
spring:
  application.name: groopy-gateway

grpc:
  server:
    security:
      enabled: false
  client:
    userService:
      address: "static://userservice:8071"
      negotiationType: PLAINTEXT
    wallService:
      address: "static://wallservice:8070"
      negotiationType: PLAINTEXT
    chatService:
      address: "static://chatservice:8072"
      negotiationType: PLAINTEXT