server:
  address: 0.0.0.0
  port: 8095
spring:
  application.name: groopy-gateway

grpc:
  server:
    security:
      enabled: false
  client:
    userService:
      address: "static://127.0.0.1:8071"
      negotiationType: PLAINTEXT
    roomService:
      address: "static://127.0.0.1:8070"
      negotiationType: PLAINTEXT