server:
  address: groopy-gateway.fly.dev
  port: 8095
spring:
  application.name: groopy-gateway

grpc:
  server:
    security:
      enabled: false
  client:
    userService:
      address: "static://user-service-3zzv.onrender.com:8071"
      negotiationType: PLAINTEXT
    wallService:
      address: "static://wall-service.fly.dev:443"
      negotiationType: PLAINTEXT