# This is a basic workflow that is manually triggered

name: Deploy

on:
   workflow_run:
     workflows: ["Docker Image Build"]
     types: [completed]

jobs:
   on-success:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
      - run: echo "Docker image built successfully"
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_DEV_HOST }}
          username: ${{ secrets.SSH_DEV_USER }}
          key: ${{ secrets.SSH_DEV_KEY }}
          script: |
                    cd groopy && bash run.sh

   on-failure:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
     steps:
       - run: echo "Docker image build UNSUCCESSFULLY"
